# Generated by Django 4.2.9 on 2024-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
